'use strict';

// Reusable item/record fixtures for tests. Mirrors the shape produced by flattenItem/flattenRecord.

const PASS_ITEM = {
  id: "1",
  itemName: "Incoming form answer",
  url: "https://monday.com/boards/1/items/1",
  employee: "John Smith",
  manager: "Jane Manager",
  office: "Orlando",
  date: "2024-03-15",
  serviceType: "Quarterly",
  isComplete: true,
  arrivedOnTime: "YES",
  professionalGreeting: "YES",
  properExplanation: "YES",
  addressedConcerns: "YES",
  extDeWebbed: "Complete",
  extGranular: "Complete",
  extPerimeterSpray: "Complete",
  extDust: "Complete",
  intLivingAreas: "Complete",
  intBasement: "Complete",
  garage: "Complete",
  uniform: "Yes",
  ppe: "Yes",
  equipmentWorking: "YES",
  chemicalsOrganized: "YES",
  professionalGreetingRating: 5,
  properExplanationRating: 4,
  vehicleCleanlinessRating: 5,
  insectsCovered: "Ant,Spiders,Cockroaches",
  productsCovered: "Demand CS,Delta Dust",
  equipmentUsed: "B&G,De-Webbing Pole",
  strengthsObserved: "Great attitude and thoroughness",
  areasToImprove: null,
  correctiveActionsGiven: null,
  additionalTrainingNeeded: null,
};

const FAIL_ITEM = {
  id: "2",
  itemName: "Incoming form answer",
  url: "https://monday.com/boards/1/items/2",
  employee: "Bob Tech",
  manager: "Jane Manager",
  office: "Tampa",
  date: "2024-03-20",
  serviceType: "Monthly",
  isComplete: true,
  arrivedOnTime: "NO",
  professionalGreeting: "NO",
  properExplanation: "NO",
  addressedConcerns: "NO",
  extDeWebbed: "Not Performed to FL Standards",
  extGranular: "Not Performed to FL Standards",
  extPerimeterSpray: "Not Performed to FL Standards",
  extDust: "Not Performed to FL Standards",
  intLivingAreas: "Not Performed to FL Standards",
  intBasement: "Not Performed to FL Standards",
  garage: "Not Performed to FL Standards",
  uniform: "Not In FL Uniform",
  ppe: "No",
  equipmentWorking: "NO",
  chemicalsOrganized: "NO",
  professionalGreetingRating: 1,
  properExplanationRating: 1,
  vehicleCleanlinessRating: 2,
  insectsCovered: "Ant",
  productsCovered: "Demand CS",
  equipmentUsed: "B&G",
  strengthsObserved: null,
  areasToImprove: "Everything needs work",
  correctiveActionsGiven: "Verbal warning issued",
  additionalTrainingNeeded: "Full re-training required",
};

const WARN_ITEM = {
  id: "3",
  itemName: "Incoming form answer",
  url: "https://monday.com/boards/1/items/3",
  employee: "Alice Tech",
  manager: "Sam Manager",
  office: "Orlando",
  date: "2024-02-10",
  serviceType: "Quarterly",
  isComplete: true,
  arrivedOnTime: "YES",
  professionalGreeting: "YES",
  properExplanation: "YES",
  addressedConcerns: "YES",
  extDeWebbed: "Missed a few spots",
  extGranular: "Missed a few spots",
  extPerimeterSpray: "Complete",
  extDust: "Complete",
  intLivingAreas: "Complete",
  intBasement: null,
  garage: null,
  uniform: "Missing parts",
  ppe: "Yes",
  equipmentWorking: "YES",
  chemicalsOrganized: "YES",
  professionalGreetingRating: 3,
  properExplanationRating: 4,
  vehicleCleanlinessRating: 3,
  insectsCovered: "Ant,Ticks",
  productsCovered: "Tandem",
  equipmentUsed: "Backpack Sprayer",
  strengthsObserved: "Good customer interaction",
  areasToImprove: "Exterior coverage needs improvement",
  correctiveActionsGiven: null,
  additionalTrainingNeeded: null,
};

const BLANK_ITEM = {
  id: "4",
  itemName: "Incoming form answer",
  url: "https://monday.com/boards/1/items/4",
  employee: "Dave Tech",
  manager: "Sam Manager",
  office: "Tampa",
  date: "2024-01-05",
  serviceType: "Initial",
  isComplete: true,
  arrivedOnTime: null,
  professionalGreeting: null,
  properExplanation: null,
  addressedConcerns: null,
  extDeWebbed: null,
  extGranular: null,
  extPerimeterSpray: null,
  extDust: null,
  intLivingAreas: null,
  intBasement: null,
  garage: null,
  uniform: null,
  ppe: null,
  equipmentWorking: null,
  chemicalsOrganized: null,
  professionalGreetingRating: null,
  properExplanationRating: null,
  vehicleCleanlinessRating: null,
  insectsCovered: null,
  productsCovered: null,
  equipmentUsed: null,
  strengthsObserved: null,
  areasToImprove: null,
  correctiveActionsGiven: null,
  additionalTrainingNeeded: null,
};

const NOT_HOME_ITEM = {
  ...PASS_ITEM,
  id: "5",
  employee: "Eve Tech",
  professionalGreeting: "Customer Not Home",
  properExplanation: "Customer Not Home",
  addressedConcerns: "Customer Not Home",
};

const INCOMPLETE_ITEM = {
  id: "6",
  employee: "Ghost Tech",
  manager: null,
  office: null,
  date: null,
  isComplete: false,
  arrivedOnTime: "YES",
};

// Raw monday.com GraphQL response shape for flattenItem tests
function makeRawItem(overrides = {}) {
  const defaults = {
    id: "100",
    name: "Incoming form answer",
    url: "https://monday.com/boards/1/items/100",
    column_values: [
      { id: "board_relation_mkyfavcb", type: "board_relation", linked_items: [{ id: "99", name: "Test Employee" }] },
      { id: "lookup_mkyf5c2t", type: "mirror", display_value: "Test Manager" },
      { id: "lookup_mkyfjte3", type: "mirror", display_value: "Test Office" },
      { id: "date_mkyfk9e2", type: "date", text: "2024-06-01" },
      { id: "dropdown_mkyf4abk", type: "dropdown", text: "Quarterly" },
      { id: "color_mkyftz1a", type: "color", text: "YES" },
      { id: "color_mkyfpwv8", type: "color", text: "YES" },
      { id: "rating_mkyfvenm", type: "rating", text: "4" },
      { id: "color_mkyfhex6", type: "color", text: "YES" },
      { id: "rating_mkyfbgn2", type: "rating", text: "5" },
      { id: "color_mkyfjys8", type: "color", text: "YES" },
      { id: "color_mkyf9dc1", type: "color", text: "Complete" },
      { id: "color_mkyfdrqk", type: "color", text: "Complete" },
      { id: "color_mkyfqthm", type: "color", text: "Complete" },
      { id: "color_mm0nh27h", type: "color", text: "Complete" },
      { id: "color_mkyfvj0t", type: "color", text: "Complete" },
      { id: "color_mkyfs4k5", type: "color", text: "" },
      { id: "color_mkyfhyds", type: "color", text: "" },
      { id: "color_mkyf4rjk", type: "color", text: "Yes" },
      { id: "color_mkyf8z73", type: "color", text: "Yes" },
      { id: "rating_mkyfw2es", type: "rating", text: "5" },
      { id: "long_text_mkyffrkt", type: "long_text", text: "Good work" },
      { id: "long_text_mkyfjhdk", type: "long_text", text: "" },
      { id: "long_text_mkyfqbp0", type: "long_text", text: "" },
      { id: "long_text_mkyfwc13", type: "long_text", text: "" },
      { id: "color_mkyg7e4w", type: "color", text: "YES" },
      { id: "color_mkygkhj2", type: "color", text: "YES" },
      { id: "dropdown_mkyfj2sj", type: "dropdown", text: "Ant,Spiders" },
      { id: "dropdown_mkyf654s", type: "dropdown", text: "Demand CS" },
      { id: "dropdown_mkyfw0qs", type: "dropdown", text: "B&G" },
    ],
  };
  return { ...defaults, ...overrides };
}

// Raw monday.com GraphQL response for flattenRecord tests
function makeRawRecord(overrides = {}) {
  const defaults = {
    id: "200",
    name: "Call Out",
    column_values: [
      { id: "board_relation_mkw07eht", type: "board_relation", linked_items: [{ id: "99", name: "Test Employee" }] },
      { id: "lookup_mkw0seqz", type: "mirror", display_value: "Test Manager" },
      { id: "lookup_mkw0jrc2", type: "mirror", display_value: "Test Office" },
      { id: "color_mkx0z6pj", type: "color", text: "Full Day" },
      { id: "timerange_mkx65krk", type: "timeline", from: "2024-04-01", to: "2024-04-01" },
      { id: "date_mkx6nxyk", type: "date", text: "" },
      { id: "date_mkx6wamm", type: "date", text: "" },
      { id: "color_mkxfev8f", type: "color", text: "Sick" },
      { id: "text_mkxxjqfj", type: "text", text: "" },
      { id: "status", type: "status", text: "Approved" },
    ],
  };
  return { ...defaults, ...overrides };
}

module.exports = {
  PASS_ITEM, FAIL_ITEM, WARN_ITEM, BLANK_ITEM, NOT_HOME_ITEM, INCOMPLETE_ITEM,
  makeRawItem, makeRawRecord,
};
